import type { CaseItem } from "@/types/crm";

export const mockCases: CaseItem[] = [
  {
    id: "case-001",
    caseNumber: "BBMC-2026-001847",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Complaint",
    subType: "Billing Dispute",
    status: "In Progress",
    priority: "High",
    slaStatus: "At Risk",
    slaDeadline: "12/02/2026 17:00",
    slaTimeRemaining: "1d 14h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "07/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Customer is disputing the January invoice for NMI 3012345678. They believe the demand charges are incorrect based on their contracted rate schedule. Requesting a review of the metering data and recalculation of charges.",
    resolution: "",
    communications: [
      {
        id: "comm-001",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "RE: January Invoice Query - LM-0045721",
        body: "Hi Priya,\n\nFollowing up on our call yesterday. I've attached the meter data from our side which shows significantly different readings to what's on the invoice.\n\nOur demand peak for January was 2,450 kW but the invoice shows 3,100 kW. This doesn't align with our operational logs.\n\nCan you please escalate this to your metering team urgently? We need this resolved before the payment due date on 15/02.\n\nRegards,\nJames Whitfield\nEnergy Manager\nBowen Basin Mining Corp",
        timestamp: "10/02/2026 09:14",
        attachments: [
          {
            id: "att-001",
            name: "Meter_Data_Jan2026.xlsx",
            type: "spreadsheet",
            size: "245 KB",
            uploadedBy: "James Whitfield",
            uploadedDate: "10/02/2026",
          },
        ],
      },
      {
        id: "comm-002",
        type: "Email",
        direction: "Outbound",
        from: "p.sharma@tallyenergy.com.au",
        to: "j.whitfield@bowenbasin.com.au",
        subject: "RE: January Invoice Query - LM-0045721",
        body: "Hi James,\n\nThank you for providing the meter data. I've forwarded this to our metering team for comparison against our records.\n\nI've also requested a manual read from the network to verify the interval data. We should have the results within 24-48 hours.\n\nI'll keep you updated on progress.\n\nKind regards,\nJohn Smith\nLarge Market Support",
        timestamp: "10/02/2026 10:30",
        attachments: [],
      },
      {
        id: "comm-003",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "January Invoice Query - LM-0045721",
        body: "Dear Support Team,\n\nI'm writing regarding our January 2026 invoice for account LM-0045721. The demand charges appear significantly higher than expected based on our contracted rate schedule.\n\nPlease investigate and provide a breakdown of the metering data used for the calculation.\n\nRegards,\nJames Whitfield",
        timestamp: "07/02/2026 14:22",
        attachments: [],
      },
      {
        id: "comm-015",
        type: "Phone",
        direction: "Inbound",
        from: "James Whitfield",
        to: "John Smith",
        subject: "Call: Demand charge discrepancy follow-up",
        loggedBy: "John Smith",
        body: "James called to follow up on the invoice dispute. He mentioned their on-site SCADA system recorded a max demand of 2,450 kW during January, whereas the invoice reflects 3,100 kW.\n\nHe suspects the meter may have recorded a spike during a planned shutdown/restart sequence on 18 Jan which shouldn't count under their contracted demand reset rules.\n\nAgreed to request interval data from the network and cross-reference with the customer's SCADA logs. James will send the SCADA export by end of day.",
        timestamp: "09/02/2026 15:40",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-001",
        type: "Email Received",
        description: "Follow-up email received from James Whitfield with meter data attachment",
        user: "System",
        timestamp: "10/02/2026 09:14",
      },
      {
        id: "act-002",
        type: "Email Sent",
        description: "Response sent to customer confirming metering team review",
        user: "John Smith",
        timestamp: "10/02/2026 10:30",
      },
      {
        id: "act-003",
        type: "Assignment",
        description: "Case assigned to John Smith from queue",
        user: "John Smith",
        timestamp: "07/02/2026 15:00",
      },
      {
        id: "act-004",
        type: "Status Change",
        description: "Status changed from New to In Progress",
        user: "John Smith",
        timestamp: "07/02/2026 15:00",
        metadata: { from: "New", to: "In Progress" },
      },
      {
        id: "act-005",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "07/02/2026 14:22",
      },
    ],
    attachments: [
      {
        id: "att-001",
        name: "Meter_Data_Jan2026.xlsx",
        type: "spreadsheet",
        size: "245 KB",
        uploadedBy: "James Whitfield",
        uploadedDate: "10/02/2026",
      },
      {
        id: "att-002",
        name: "Invoice_Jan2026_LM0045721.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadedBy: "System",
        uploadedDate: "07/02/2026",
      },
    ],
    relatedCases: ["BBMC-2026-001745", "BBMC-2026-001882"],
  },
  {
    id: "case-002",
    caseNumber: "GAS-2026-001832",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "EWR",
    subType: "Meter Replacement",
    status: "Pending",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "20/02/2026 17:00",
    slaTimeRemaining: "10d 8h",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "03/02/2026",
    updatedDate: "08/02/2026",
    description:
      "Embedded works request for meter replacement at NMI 3098765434. Current CT meter is due for scheduled replacement as per the compliance programme. Network provider has been engaged.",
    resolution: "",
    communications: [
      {
        id: "comm-004",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "m.torres@gladstone-aluminium.com.au",
        subject: "EWR Update - Meter Replacement NMI 3098765434",
        body: "Hi Michael,\n\nJust a quick update on the meter replacement. Ergon has confirmed the site visit for 18/02/2026 between 08:00 and 12:00.\n\nPlease ensure site access is available and a representative can meet the technician at the main gate.\n\nRegards,\nDaniel Cooper",
        timestamp: "08/02/2026 11:45",
        attachments: [],
      },
      {
        id: "comm-016",
        type: "Phone",
        direction: "Outbound",
        from: "Daniel Cooper",
        to: "Michael Torres",
        subject: "Call: Confirm site access for meter replacement",
        loggedBy: "Daniel Cooper",
        body: "Called Michael to confirm logistics for the 18/02 meter replacement visit. He confirmed a site supervisor will be available at the main gate from 07:45.\n\nMichael flagged that there's a planned pot-line maintenance on the same day — asked if the meter swap could cause any supply interruption. Confirmed with him that the CT replacement is a like-for-like swap with a brief isolation (approx 15 min) which has been coordinated with Ergon.\n\nNo further concerns raised. Michael will email the site induction form.",
        timestamp: "10/02/2026 09:20",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-006",
        type: "Email Sent",
        description: "Site visit confirmation sent to customer",
        user: "Daniel Cooper",
        timestamp: "08/02/2026 11:45",
      },
      {
        id: "act-007",
        type: "Status Change",
        description: "Status changed from In Progress to Pending",
        user: "Daniel Cooper",
        timestamp: "06/02/2026 09:00",
        metadata: { from: "In Progress", to: "Pending" },
      },
      {
        id: "act-008",
        type: "Created",
        description: "EWR created for scheduled meter replacement",
        user: "Daniel Cooper",
        timestamp: "03/02/2026 10:15",
      },
    ],
    attachments: [
      {
        id: "att-003",
        name: "EWR_Form_3098765434.pdf",
        type: "pdf",
        size: "890 KB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "03/02/2026",
      },
    ],
    relatedCases: ["GAS-2026-001750", "GAS-2026-001860"],
    pendingReason: "3rd Party",
  },
  {
    id: "case-003",
    caseNumber: "MSMO-2026-001790",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "Enquiry",
    subType: "Rate Review",
    status: "New",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "17/02/2026 17:00",
    slaTimeRemaining: "7d 2h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "05/02/2026",
    updatedDate: "05/02/2026",
    description:
      "Customer requesting a review of their current rate schedule ahead of contract renewal in September 2027. They want to explore green energy options and potential for PPA arrangements.",
    resolution: "",
    communications: [
      {
        id: "comm-005",
        type: "Email",
        direction: "Inbound",
        from: "d.patterson@mackaysugar.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Rate Schedule Review Request - LM-0046102",
        body: "Dear Tally Energy Team,\n\nWe're looking to review our current rate schedule and explore options for our upcoming contract renewal. Specifically interested in:\n\n1. Green energy certificate options\n2. PPA arrangements with local solar farms\n3. Time-of-use rate optimisation\n\nCould someone from your large market team arrange a meeting to discuss?\n\nBest regards,\nDavid Patterson",
        timestamp: "05/02/2026 08:30",
        attachments: [],
      },
      {
        id: "comm-017",
        type: "Phone",
        direction: "Outbound",
        from: "John Smith",
        to: "David Patterson",
        subject: "Call: Initial rate review discussion",
        loggedBy: "John Smith",
        body: "Introductory call with David Patterson regarding rate review ahead of contract renewal.\n\nKey points discussed:\n- Current flat rate is $68/MWh; customer believes TOU could save 10-15% given their crushing season is primarily overnight\n- Interested in bundling LGCs to meet their sustainability targets — board mandate to reach 50% renewables by 2028\n- Open to a PPA with a local solar farm (mentioned Collinsville Solar Farm as a possibility)\n- David requested a modelling pack showing flat vs TOU vs blended PPA scenarios\n\nNext steps: Prepare rate comparison modelling and schedule a follow-up meeting in 2 weeks with the commercial team.",
        timestamp: "06/02/2026 14:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-009",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "05/02/2026 08:30",
      },
    ],
    attachments: [],
    relatedCases: ["MSMO-2026-001870", "MSMO-2026-001900"],
  },
  {
    id: "case-004",
    caseNumber: "BCC-2026-001855",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Complaint",
    subType: "Service Quality",
    status: "In Progress",
    priority: "Critical",
    slaStatus: "Breached",
    slaDeadline: "09/02/2026 12:00",
    slaTimeRemaining: "Overdue by 22h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "08/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Customer experienced two unplanned outages in the past week affecting event operations. Requesting urgent investigation and compensation for lost revenue from cancelled bookings.",
    resolution: "",
    communications: [
      {
        id: "comm-006",
        type: "Phone",
        direction: "Inbound",
        from: "Amanda Foster",
        to: "John Smith",
        subject: "Urgent: Repeated Outages at Convention Centre",
        loggedBy: "John Smith",
        body: "Phone call received from Amanda Foster regarding second power outage in 5 days. Convention centre had to cancel a corporate gala dinner affecting 350 guests. Customer extremely dissatisfied and requesting immediate escalation to management. Mentioned potential ombudsman complaint if not resolved promptly.",
        timestamp: "10/02/2026 08:15",
        attachments: [],
      },
      {
        id: "comm-007",
        type: "Email",
        direction: "Inbound",
        from: "a.foster@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "URGENT: Second Power Outage - Requesting Immediate Action",
        body: "Dear Tally Energy,\n\nThis is completely unacceptable. We have now experienced two unplanned outages within 5 days:\n\n- 03/02 at 18:45 - Power loss for 2.5 hours during wedding reception\n- 08/02 at 14:30 - Power loss for 45 minutes during corporate event setup\n\nWe have lost significant revenue and our reputation with clients is being damaged. We require:\n\n1. Immediate root cause analysis\n2. A guaranteed remediation plan\n3. Compensation for lost revenue (estimated $85,000)\n\nIf this is not resolved within 24 hours, we will be filing a formal complaint with the Energy Ombudsman.\n\nAmanda Foster\nFacilities Manager",
        timestamp: "08/02/2026 16:20",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-010",
        type: "Email Received",
        description: "Urgent complaint email received regarding repeated outages",
        user: "System",
        timestamp: "08/02/2026 16:20",
      },
      {
        id: "act-011",
        type: "SLA Update",
        description: "SLA breached — response deadline exceeded",
        user: "System",
        timestamp: "09/02/2026 12:00",
      },
      {
        id: "act-012",
        type: "Assignment",
        description: "Case escalated and assigned to John Smith",
        user: "Team Lead",
        timestamp: "09/02/2026 08:30",
      },
      {
        id: "act-013",
        type: "Created",
        description: "Case created from urgent inbound email",
        user: "System",
        timestamp: "08/02/2026 16:20",
      },
    ],
    attachments: [],
    relatedCases: ["BCC-2026-001890", "BCC-2026-001910"],
  },
  {
    id: "case-005",
    caseNumber: "TPA-2026-001720",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "Onboarding",
    subType: "New Connection",
    status: "Resolved",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "15/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "20/01/2026",
    updatedDate: "09/02/2026",
    description:
      "New meter connection for expansion to berth 14. All network applications and metering installations completed. Awaiting final energisation confirmation.",
    resolution:
      "New NMI 3045678903 successfully energised on 09/02/2026. Meter reading confirmed at 0 kWh. Customer notified and billing configuration set up for the new site.",
    communications: [
      {
        id: "comm-008",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "k.mitchell@townsvilleport.com.au",
        subject: "Connection Complete - NMI 3045678903 Energised",
        body: "Hi Karen,\n\nGreat news — the new connection at Berth 14 has been successfully energised. NMI 3045678903 is now active and the initial meter reading has been confirmed at 0 kWh.\n\nBilling will commence from the next billing cycle. Please let me know if you have any questions.\n\nRegards,\nDaniel Cooper",
        timestamp: "09/02/2026 14:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-014",
        type: "Status Change",
        description: "Status changed from In Progress to Resolved",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 14:00",
        metadata: { from: "In Progress", to: "Resolved" },
      },
      {
        id: "act-015",
        type: "Email Sent",
        description: "Completion notification sent to customer",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 14:00",
      },
      {
        id: "act-016",
        type: "Created",
        description: "Onboarding case created for new berth 14 connection",
        user: "Daniel Cooper",
        timestamp: "20/01/2026 09:00",
      },
    ],
    attachments: [
      {
        id: "att-004",
        name: "Network_Application_B14.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "20/01/2026",
      },
      {
        id: "att-005",
        name: "Energisation_Certificate.pdf",
        type: "pdf",
        size: "540 KB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "09/02/2026",
      },
    ],
    relatedCases: [],
  },
  {
    id: "case-006",
    caseNumber: "GAS-2026-001860",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "Dunning",
    subType: "Payment Reminder",
    status: "New",
    priority: "High",
    slaStatus: "On Track",
    slaDeadline: "14/02/2026 17:00",
    slaTimeRemaining: "4d 6h",
    owner: "Unassigned",
    team: "Collections",
    createdDate: "10/02/2026",
    updatedDate: "10/02/2026",
    description:
      "Automated dunning workflow triggered for overdue gas invoice. Payment of $312,000 was due on 31/01/2026. Second reminder to be issued.",
    resolution: "",
    communications: [],
    activities: [
      {
        id: "act-017",
        type: "Created",
        description: "Dunning case auto-created for overdue gas invoice",
        user: "System",
        timestamp: "10/02/2026 06:00",
      },
    ],
    attachments: [
      { id: "att-c006-01", name: "Invoice_Jan2026_Overdue.pdf", type: "pdf", size: "245 KB", uploadedBy: "System", uploadedDate: "10/02/2026" },
      { id: "att-c006-02", name: "Payment_Reminder_First.pdf", type: "pdf", size: "120 KB", uploadedBy: "System", uploadedDate: "05/02/2026" },
      { id: "att-c006-03", name: "Statement_Jan2026.xlsx", type: "spreadsheet", size: "89 KB", uploadedBy: "Collections", uploadedDate: "10/02/2026" },
      { id: "att-c006-04", name: "Contract_Gladstone_Aluminium.pdf", type: "pdf", size: "1.2 MB", uploadedBy: "System", uploadedDate: "15/01/2026" },
      { id: "att-c006-05", name: "Meter_Readings_Jan2026.csv", type: "spreadsheet", size: "312 KB", uploadedBy: "System", uploadedDate: "01/02/2026" },
      { id: "att-c006-06", name: "Dunning_Letter_Draft.docx", type: "document", size: "45 KB", uploadedBy: "Collections", uploadedDate: "09/02/2026" },
      { id: "att-c006-07", name: "Account_Summary_GAS-2026-001860.pdf", type: "pdf", size: "567 KB", uploadedBy: "System", uploadedDate: "10/02/2026" },
      { id: "att-c006-08", name: "Payment_History_2025.xlsx", type: "spreadsheet", size: "198 KB", uploadedBy: "Finance", uploadedDate: "08/02/2026" },
      { id: "att-c006-09", name: "Escalation_Notes.txt", type: "document", size: "4 KB", uploadedBy: "Collections", uploadedDate: "10/02/2026" },
      { id: "att-c006-10", name: "Direct_Debit_Authority.pdf", type: "pdf", size: "89 KB", uploadedBy: "System", uploadedDate: "20/01/2025" },
      { id: "att-c006-11", name: "Rate_Schedule_Gas_2026.pdf", type: "pdf", size: "340 KB", uploadedBy: "System", uploadedDate: "01/01/2026" },
      { id: "att-c006-12", name: "Contact_Log_Gladstone.xlsx", type: "spreadsheet", size: "67 KB", uploadedBy: "Collections", uploadedDate: "09/02/2026" },
      { id: "att-c006-13", name: "Final_Notice_Template.pdf", type: "pdf", size: "112 KB", uploadedBy: "Collections", uploadedDate: "10/02/2026" },
      { id: "att-c006-14", name: "NMI_Register_Acc002.pdf", type: "pdf", size: "256 KB", uploadedBy: "System", uploadedDate: "05/02/2026" },
      { id: "att-c006-15", name: "Screenshot_Account_Portal.png", type: "image", size: "890 KB", uploadedBy: "Collections", uploadedDate: "10/02/2026" },
      { id: "att-c006-16", name: "Approval_Workflow_Notes.docx", type: "document", size: "28 KB", uploadedBy: "Collections", uploadedDate: "09/02/2026" },
      { id: "att-c006-17", name: "Billing_Dispute_History.pdf", type: "pdf", size: "445 KB", uploadedBy: "Finance", uploadedDate: "08/02/2026" },
      { id: "att-c006-18", name: "Email_Thread_Reminder_2.pdf", type: "pdf", size: "178 KB", uploadedBy: "System", uploadedDate: "10/02/2026" },
      { id: "att-c006-19", name: "Credit_Check_Result_2026.pdf", type: "pdf", size: "92 KB", uploadedBy: "Finance", uploadedDate: "01/02/2026" },
      { id: "att-c006-20", name: "Payment_Plan_Options.xlsx", type: "spreadsheet", size: "56 KB", uploadedBy: "Collections", uploadedDate: "10/02/2026" },
    ],
    relatedCases: ["GAS-2026-001750", "GAS-2026-001832"],
  },
  {
    id: "case-007",
    caseNumber: "BBMC-2026-001745",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Enquiry",
    subType: "Contract Amendment",
    status: "Closed",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "30/01/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "22/01/2026",
    updatedDate: "30/01/2026",
    description:
      "Customer requested amendment to contract terms for demand response participation programme.",
    resolution:
      "Contract amendment processed. Updated terms include demand response participation clause with agreed incentive structure. Customer signed updated agreement on 29/01/2026.",
    communications: [
      {
        id: "comm-c007-01",
        type: "Email",
        direction: "Outbound",
        from: "p.sharma@tallyenergy.com.au",
        to: "j.whitfield@bowenbasin.com.au",
        subject: "Contract Amendment — Demand Response Participation",
        body: "Hi James,\n\nPlease find the updated contract terms reflecting the demand response participation clause. The agreed incentive structure is outlined in Schedule 3.\n\nPlease sign and return at your earliest convenience.\n\nKind regards,\nJohn Smith",
        timestamp: "28/01/2026 14:00",
        attachments: [],
        loggedBy: "John Smith",
        threadId: "thread-contract-amendment-001",
      },
      {
        id: "comm-c007-02",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "p.sharma@tallyenergy.com.au",
        subject: "RE: Contract Amendment — Demand Response Participation",
        body: "Hi Priya,\n\nSigned copy attached. Thanks for turning this around quickly.\n\nRegards,\nJames Whitfield",
        timestamp: "29/01/2026 09:30",
        attachments: [],
        loggedBy: "John Smith",
        threadId: "thread-contract-amendment-001",
      },
    ],
    activities: [
      {
        id: "act-018",
        type: "Status Change",
        description: "Status changed from Resolved to Closed",
        user: "John Smith",
        timestamp: "30/01/2026 16:30",
        metadata: { from: "Resolved", to: "Closed" },
      },
      {
        id: "act-019",
        type: "Created",
        description: "Enquiry case created for contract amendment request",
        user: "John Smith",
        timestamp: "22/01/2026 11:00",
      },
    ],
    attachments: [],
    relatedCases: ["BBMC-2026-001847", "BBMC-2026-001882"],
    childCaseIds: ["case-017"],
  },
  {
    id: "case-008",
    caseNumber: "MSMO-2026-001870",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "EWR",
    subType: "Network Upgrade",
    status: "In Progress",
    priority: "High",
    slaStatus: "At Risk",
    slaDeadline: "13/02/2026 17:00",
    slaTimeRemaining: "3d 5h",
    owner: "Daniel Cooper",
    team: "Large Market Support",
    createdDate: "01/02/2026",
    updatedDate: "09/02/2026",
    description:
      "Network augmentation required for increased capacity to support new crushing line. Transformer upgrade from 5MVA to 10MVA at NMI 3054321098.",
    resolution: "",
    communications: [
      {
        id: "comm-009",
        type: "Email",
        direction: "Outbound",
        from: "d.cooper@tallyenergy.com.au",
        to: "d.patterson@mackaysugar.com.au",
        subject: "Network Upgrade Progress - NMI 3054321098",
        body: "Hi David,\n\nUpdate on the transformer upgrade:\n\n- Network design approval: Received 07/02\n- Equipment procurement: Ordered, ETA 25/02\n- Scheduled outage window: TBC\n\nI'll confirm the outage schedule once Ergon provides available dates.\n\nRegards,\nDaniel",
        timestamp: "09/02/2026 15:30",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-020",
        type: "Email Sent",
        description: "Progress update sent to customer",
        user: "Daniel Cooper",
        timestamp: "09/02/2026 15:30",
      },
      {
        id: "act-021",
        type: "Created",
        description: "EWR created for transformer upgrade",
        user: "Daniel Cooper",
        timestamp: "01/02/2026 13:00",
      },
    ],
    attachments: [
      {
        id: "att-006",
        name: "Network_Design_Approval.pdf",
        type: "pdf",
        size: "3.4 MB",
        uploadedBy: "Daniel Cooper",
        uploadedDate: "07/02/2026",
      },
    ],
    relatedCases: [],
  },
  // ── Additional cases for list-view coverage ──────────────────────────────
  {
    id: "case-009",
    caseNumber: "BBMC-2026-001882",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Enquiry",
    subType: "Tariff Information",
    status: "In Progress",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "18/02/2026 17:00",
    slaTimeRemaining: "7d 10h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "10/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer requesting detailed tariff comparison for NMI 3012345678 to evaluate whether a time-of-use structure would reduce costs during off-peak crushing operations.",
    resolution: "",
    communications: [
      {
        id: "comm-010",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Tariff comparison request",
        body: "Hi team,\n\nCould you provide a comparison of our current flat rate vs a TOU tariff? Our off-peak usage is significant and we'd like to understand savings potential.\n\nRegards,\nJames Whitfield",
        timestamp: "10/02/2026 10:00",
        attachments: [],
      },
      {
        id: "comm-018",
        type: "Phone",
        direction: "Outbound",
        from: "John Smith",
        to: "James Whitfield",
        subject: "Call: Tariff comparison scope clarification",
        loggedBy: "John Smith",
        body: "Called James to clarify the scope of the tariff comparison. He confirmed the analysis should cover NMI 3012345678 only for now, but may extend to their secondary NMI if results are favourable.\n\nJames mentioned they run a 24/7 operation but load drops significantly between 22:00–06:00 (down to ~40% of daytime demand). Wants the comparison modelled over the past 12 months of interval data.\n\nAgreed to deliver the comparison within 5 business days.",
        timestamp: "11/02/2026 09:15",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-022",
        type: "Assignment",
        description: "Case assigned to John Smith",
        user: "John Smith",
        timestamp: "10/02/2026 11:00",
      },
      {
        id: "act-023",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "10/02/2026 10:00",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  {
    id: "case-010",
    caseNumber: "BCC-2026-001890",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Complaint",
    subType: "Billing Error",
    status: "New",
    priority: "High",
    slaStatus: "On Track",
    slaDeadline: "16/02/2026 17:00",
    slaTimeRemaining: "5d 12h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer reporting duplicate charges on the February invoice. Two line items for the same NMI appear on the statement with identical amounts. Requesting immediate correction.",
    resolution: "",
    communications: [
      {
        id: "comm-019",
        type: "Phone",
        direction: "Inbound",
        from: "Amanda Foster",
        to: "John Smith",
        subject: "Call: Duplicate billing charges on Feb invoice",
        loggedBy: "John Smith",
        body: "Amanda called to report duplicate charges on the February invoice. She identified two identical line items for NMI 3067890123 — both showing $14,320 for demand charges.\n\nShe confirmed only one meter is active at that NMI. Suspects an issue with the billing system picking up a decommissioned virtual NMI that was merged last year.\n\nAsked for a corrected invoice to be issued urgently as their accounts payable team has flagged it and is withholding payment until resolved.",
        timestamp: "11/02/2026 10:30",
        attachments: [],
      },
      {
        id: "comm-011",
        type: "Email",
        direction: "Inbound",
        from: "a.foster@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Duplicate charges on Feb invoice",
        body: "Hi,\n\nOur February invoice shows two identical charges of $14,200 for NMI 3067890123. This looks like a duplicate. Please investigate and issue a corrected invoice.\n\nThanks,\nAmanda Foster",
        timestamp: "11/02/2026 09:00",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-024",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "11/02/2026 09:00",
      },
    ],
    attachments: [],
    relatedCases: ["BCC-2026-001855"],
  },
  {
    id: "case-011",
    caseNumber: "TPA-2026-001895",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "EWR",
    subType: "Solar Installation",
    status: "Pending",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "28/02/2026 17:00",
    slaTimeRemaining: "17d 8h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "06/02/2026",
    updatedDate: "10/02/2026",
    description:
      "EWR for rooftop solar installation at Berth 14 office building. 150kW system. Awaiting network study results from Ergon before proceeding with installation approval.",
    resolution: "",
    communications: [],
    activities: [
      {
        id: "act-025",
        type: "Status Change",
        description: "Status changed from In Progress to Pending — awaiting network study",
        user: "John Smith",
        timestamp: "10/02/2026 14:00",
        metadata: { from: "In Progress", to: "Pending" },
      },
      {
        id: "act-026",
        type: "Created",
        description: "EWR created for solar installation",
        user: "John Smith",
        timestamp: "06/02/2026 09:30",
      },
    ],
    attachments: [
      {
        id: "att-007",
        name: "Solar_Design_150kW_B14.pdf",
        type: "pdf",
        size: "5.8 MB",
        uploadedBy: "John Smith",
        uploadedDate: "06/02/2026",
      },
    ],
    relatedCases: ["TPA-2026-001720", "TPA-2026-001780"],
    pendingReason: "On Hold",
  },
  {
    id: "case-012",
    caseNumber: "GAS-2026-001750",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "Enquiry",
    subType: "Account Information",
    status: "Closed",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "03/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "27/01/2026",
    updatedDate: "02/02/2026",
    description:
      "Customer requested updated statement of account for their finance team's quarterly reporting. Sent consolidated statement covering all three NMIs.",
    resolution:
      "Consolidated statement for NMIs 3098765432, 3098765433, and 3098765434 generated and emailed to customer on 02/02/2026. No outstanding issues.",
    communications: [
      {
        id: "comm-c012-01",
        type: "Email",
        direction: "Outbound",
        from: "j.smith@tallyenergy.com.au",
        to: "m.torres@gladstone-aluminium.com.au",
        subject: "Statement of Account — Gladstone Aluminium Smelter",
        body: "Hi Michael,\n\nPlease find attached the consolidated statement covering all three NMIs for Q4 2025. Let me know if you need any further detail.\n\nRegards,\nJohn Smith",
        timestamp: "02/02/2026 11:00",
        attachments: [],
        loggedBy: "John Smith",
        threadId: "thread-statement-gas-001",
      },
    ],
    activities: [
      {
        id: "act-027",
        type: "Status Change",
        description: "Status changed from Resolved to Closed",
        user: "John Smith",
        timestamp: "02/02/2026 16:00",
        metadata: { from: "Resolved", to: "Closed" },
      },
      {
        id: "act-028",
        type: "Created",
        description: "Enquiry created for statement of account request",
        user: "John Smith",
        timestamp: "27/01/2026 10:00",
      },
    ],
    attachments: [],
    relatedCases: ["GAS-2026-001832", "GAS-2026-001860"],
    childCaseIds: ["case-018"],
  },
  {
    id: "case-013",
    caseNumber: "MSMO-2026-001900",
    accountId: "acc-003",
    accountName: "Mackay Sugar Mill Operations",
    type: "Onboarding",
    subType: "Meter Installation",
    status: "New",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "25/02/2026 17:00",
    slaTimeRemaining: "14d 6h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "New meter installation required for additional processing shed. Customer has submitted the electrical works request form. Awaiting assignment to field operations team.",
    resolution: "",
    communications: [
      {
        id: "comm-012",
        type: "Email",
        direction: "Inbound",
        from: "d.patterson@mackaysugar.com.au",
        to: "support@tallyenergy.com.au",
        subject: "New meter for processing shed B",
        body: "Hi team,\n\nPlease find attached the EWR form for a new meter at our processing shed B. We need this operational by end of March.\n\nRegards,\nDavid Patterson",
        timestamp: "11/02/2026 07:45",
        attachments: [
          {
            id: "att-008",
            name: "EWR_Processing_Shed_B.pdf",
            type: "pdf",
            size: "1.1 MB",
            uploadedBy: "David Patterson",
            uploadedDate: "11/02/2026",
          },
        ],
      },
    ],
    activities: [
      {
        id: "act-029",
        type: "Created",
        description: "Case created from inbound email with attachment",
        user: "System",
        timestamp: "11/02/2026 07:45",
      },
    ],
    attachments: [
      {
        id: "att-008",
        name: "EWR_Processing_Shed_B.pdf",
        type: "pdf",
        size: "1.1 MB",
        uploadedBy: "David Patterson",
        uploadedDate: "11/02/2026",
      },
    ],
    relatedCases: [],
  },
  {
    id: "case-014",
    caseNumber: "BBMC-2026-001905",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Dunning",
    subType: "Final Notice",
    status: "In Progress",
    priority: "Critical",
    slaStatus: "At Risk",
    slaDeadline: "13/02/2026 12:00",
    slaTimeRemaining: "1d 23h",
    owner: "John Smith",
    team: "Collections",
    createdDate: "09/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Final notice stage for overdue electricity invoice. Amount owing: $187,500. Previous reminders sent on 20/01 and 03/02. Customer has been contacted by phone; payment plan under discussion.",
    resolution: "",
    communications: [
      {
        id: "comm-013",
        type: "Phone",
        direction: "Outbound",
        from: "John Smith",
        to: "James Whitfield",
        subject: "Payment plan discussion — final notice",
        loggedBy: "John Smith",
        body: "Called James Whitfield to discuss the overdue balance. Customer acknowledged the debt and proposed a payment plan of 3 monthly instalments. Awaiting finance team approval of the plan before confirming with the customer.",
        timestamp: "11/02/2026 14:30",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-030",
        type: "Comment",
        description: "Customer proposed 3-month payment plan. Sent to finance for approval.",
        user: "John Smith",
        timestamp: "11/02/2026 14:45",
      },
      {
        id: "act-031",
        type: "Created",
        description: "Final notice dunning case auto-created",
        user: "System",
        timestamp: "09/02/2026 06:00",
      },
    ],
    attachments: [],
    relatedCases: ["GAS-2026-001860"],
  },
  {
    id: "case-015",
    caseNumber: "BCC-2026-001910",
    accountId: "acc-004",
    accountName: "Brisbane Convention Centre",
    type: "Enquiry",
    subType: "Green Energy Options",
    status: "New",
    priority: "Low",
    slaStatus: "On Track",
    slaDeadline: "20/02/2026 17:00",
    slaTimeRemaining: "9d 4h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "11/02/2026",
    updatedDate: "11/02/2026",
    description:
      "Customer interested in carbon offset programme and GreenPower options for their next contract period. Sustainability initiative driven by venue marketing requirements.",
    resolution: "",
    communications: [
      {
        id: "comm-014",
        type: "Email",
        direction: "Inbound",
        from: "t.richards@brisbanecc.com.au",
        to: "support@tallyenergy.com.au",
        subject: "Green energy and carbon offset enquiry",
        body: "Dear Tally Energy,\n\nAs part of our sustainability commitment, we'd like to explore GreenPower and carbon offset options for our next contract. Could someone provide an overview of available programmes and indicative pricing?\n\nKind regards,\nTom Richards\nCFO",
        timestamp: "11/02/2026 11:15",
        attachments: [],
      },
    ],
    activities: [
      {
        id: "act-032",
        type: "Created",
        description: "Case created from inbound email",
        user: "System",
        timestamp: "11/02/2026 11:15",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  {
    id: "case-016",
    caseNumber: "TPA-2026-001780",
    accountId: "acc-005",
    accountName: "Townsville Port Authority",
    type: "Complaint",
    subType: "Delayed Response",
    status: "Resolved",
    priority: "Medium",
    slaStatus: "On Track",
    slaDeadline: "08/02/2026 17:00",
    slaTimeRemaining: "N/A",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "01/02/2026",
    updatedDate: "07/02/2026",
    description:
      "Customer complained about a 5-day delay in responding to their initial meter query. Investigated and found the email was routed to the wrong queue. Process corrected.",
    resolution:
      "Root cause identified as incorrect email routing rule. Rule updated to ensure Townsville Port queries route to Large Market Support. Customer accepted apology and is satisfied with the corrective action.",
    communications: [],
    activities: [
      {
        id: "act-033",
        type: "Status Change",
        description: "Status changed from In Progress to Resolved",
        user: "John Smith",
        timestamp: "07/02/2026 15:00",
        metadata: { from: "In Progress", to: "Resolved" },
      },
      {
        id: "act-034",
        type: "Created",
        description: "Complaint case created",
        user: "John Smith",
        timestamp: "01/02/2026 08:00",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  // ── Child cases (spawned from post-closure replies) ────────────────────
  {
    id: "case-017",
    caseNumber: "BBMC-2026-001920",
    accountId: "acc-001",
    accountName: "Bowen Basin Mining Corp",
    type: "Complaint",
    subType: "Billing Dispute",
    status: "New",
    priority: "High",
    slaStatus: "On Track",
    slaDeadline: "28/02/2026 17:00",
    slaTimeRemaining: "4d 0h",
    owner: "Unassigned",
    team: "Large Market Support",
    createdDate: "18/02/2026",
    updatedDate: "18/02/2026",
    description:
      "Customer replied on the closed contract amendment email thread disputing an incentive payment that was promised as part of the demand response clause but not reflected on the February invoice. Auto-created as child case (cool-off period exceeded).",
    resolution: "",
    parentCaseId: "case-007",
    parentCaseNumber: "BBMC-2026-001745",
    communications: [
      {
        id: "comm-c017-01",
        type: "Email",
        direction: "Inbound",
        from: "j.whitfield@bowenbasin.com.au",
        to: "p.sharma@tallyenergy.com.au",
        subject: "RE: Contract Amendment — Demand Response Participation",
        body: "Hi Priya,\n\nI'm looking at our February invoice and the demand response incentive we agreed to in the contract amendment isn't showing up. The signed agreement clearly states a $12,500 monthly credit from February onwards.\n\nThis bill is wrong — where's our compensation? Can you please look into this urgently and issue a corrected invoice?\n\nRegards,\nJames Whitfield\nEnergy Manager\nBowen Basin Mining Corp",
        timestamp: "18/02/2026 08:45",
        attachments: [],
        loggedBy: "System",
        threadId: "thread-contract-amendment-001",
      },
      {
        id: "comm-c017-02",
        type: "System",
        direction: "Internal",
        from: "System",
        to: "",
        subject: "Child case auto-created",
        body: "This case was automatically created because a customer reply was received on a closed case thread (BBMC-2026-001745) outside the 48-hour cool-off window. The reply arrived 19 days after case closure.",
        timestamp: "18/02/2026 08:45",
        attachments: [],
        loggedBy: "System",
      },
    ],
    activities: [
      {
        id: "act-c017-01",
        type: "Created",
        description: "Child case auto-created from reply on closed case BBMC-2026-001745 (cool-off period exceeded — 19 days after closure)",
        user: "System",
        timestamp: "18/02/2026 08:45",
      },
      {
        id: "act-c017-02",
        type: "Email Received",
        description: "Inbound email from James Whitfield disputing missing demand response incentive on February invoice",
        user: "System",
        timestamp: "18/02/2026 08:45",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
  {
    id: "case-018",
    caseNumber: "GAS-2026-001925",
    accountId: "acc-002",
    accountName: "Gladstone Aluminium Smelter",
    type: "Complaint",
    subType: "Billing Dispute",
    status: "In Progress",
    priority: "Medium",
    slaStatus: "At Risk",
    slaDeadline: "25/02/2026 17:00",
    slaTimeRemaining: "2d 8h",
    owner: "John Smith",
    team: "Large Market Support",
    createdDate: "15/02/2026",
    updatedDate: "20/02/2026",
    description:
      "Customer reviewed the consolidated statement that was sent as part of the closed case and identified a discrepancy in NMI 3098765433 charges. Reply arrived 13 days after the parent case was closed, triggering auto-creation of this child case.",
    resolution: "",
    parentCaseId: "case-012",
    parentCaseNumber: "GAS-2026-001750",
    communications: [
      {
        id: "comm-c018-01",
        type: "Email",
        direction: "Inbound",
        from: "m.torres@gladstone-aluminium.com.au",
        to: "j.smith@tallyenergy.com.au",
        subject: "RE: Statement of Account — Gladstone Aluminium Smelter",
        body: "Hi John,\n\nThanks for sending through the consolidated statement. Our finance team has been reviewing it and we've found a discrepancy on NMI 3098765433.\n\nThe network charges for November show $42,300 but our records from Ergon indicate the actual network pass-through should have been $38,750. That's a $3,550 overcharge.\n\nCan you investigate and confirm whether we're owed a credit?\n\nRegards,\nMichael Torres\nFinance Manager\nGladstone Aluminium Smelter",
        timestamp: "15/02/2026 10:20",
        attachments: [],
        loggedBy: "System",
        threadId: "thread-statement-gas-001",
      },
      {
        id: "comm-c018-02",
        type: "System",
        direction: "Internal",
        from: "System",
        to: "",
        subject: "Child case auto-created",
        body: "This case was automatically created because a customer reply was received on a closed case thread (GAS-2026-001750) outside the 48-hour cool-off window. The reply arrived 13 days after case closure.",
        timestamp: "15/02/2026 10:20",
        attachments: [],
        loggedBy: "System",
      },
      {
        id: "comm-c018-03",
        type: "Email",
        direction: "Outbound",
        from: "j.smith@tallyenergy.com.au",
        to: "m.torres@gladstone-aluminium.com.au",
        subject: "RE: Statement of Account — Gladstone Aluminium Smelter",
        body: "Hi Michael,\n\nThanks for flagging this. I've pulled the network invoices for November and I can see the discrepancy you're referring to.\n\nI've raised this with our billing team and we're cross-checking against the Ergon settlement data. I'll have an answer for you by end of week.\n\nRegards,\nJohn Smith\nLarge Market Support",
        timestamp: "16/02/2026 09:15",
        attachments: [],
        loggedBy: "John Smith",
        threadId: "thread-statement-gas-001",
      },
      {
        id: "comm-c018-04",
        type: "Note",
        direction: "Internal",
        from: "John Smith",
        to: "",
        subject: "Investigation notes — network charge discrepancy",
        body: "Checked Ergon settlement data for NMI 3098765433 Nov 2025. Ergon billed us $38,750 but our system applied a $42,300 charge to the customer. Likely caused by the rate table update in October that wasn't applied correctly to this NMI. Billing team confirmed — credit of $3,550 to be issued on the March invoice.",
        timestamp: "20/02/2026 11:30",
        attachments: [],
        loggedBy: "John Smith",
      },
    ],
    activities: [
      {
        id: "act-c018-01",
        type: "Created",
        description: "Child case auto-created from reply on closed case GAS-2026-001750 (cool-off period exceeded — 13 days after closure)",
        user: "System",
        timestamp: "15/02/2026 10:20",
      },
      {
        id: "act-c018-02",
        type: "Email Received",
        description: "Inbound email from Michael Torres reporting network charge discrepancy on NMI 3098765433",
        user: "System",
        timestamp: "15/02/2026 10:20",
      },
      {
        id: "act-c018-03",
        type: "Assignment",
        description: "Case assigned to John Smith",
        user: "John Smith",
        timestamp: "15/02/2026 14:00",
      },
      {
        id: "act-c018-04",
        type: "Status Change",
        description: "Status changed from New to In Progress",
        user: "John Smith",
        timestamp: "15/02/2026 14:00",
        metadata: { from: "New", to: "In Progress" },
      },
      {
        id: "act-c018-05",
        type: "Email Sent",
        description: "Response sent to customer confirming investigation",
        user: "John Smith",
        timestamp: "16/02/2026 09:15",
      },
      {
        id: "act-c018-06",
        type: "Note Added",
        description: "Internal note added — confirmed $3,550 overcharge, credit to be issued",
        user: "John Smith",
        timestamp: "20/02/2026 11:30",
      },
    ],
    attachments: [],
    relatedCases: [],
  },
];

export function getCaseById(id: string): CaseItem | undefined {
  return mockCases.find((c) => c.id === id);
}

export function getCaseByCaseNumber(caseNumber: string): CaseItem | undefined {
  return mockCases.find((c) => c.caseNumber === caseNumber);
}

export function getCasesBySLA(status: string): CaseItem[] {
  return mockCases.filter((c) => c.slaStatus === status);
}

export function getCasesByAccountId(accountId: string): CaseItem[] {
  return mockCases.filter((c) => c.accountId === accountId);
}
