export const MOCK_NOTE_TEMPLATES = [
  {
    id: "tpl-01",
    name: "Resolution Summary",
    title: "Case Resolved",
    body: "This case has been resolved.\n\nRoot cause: [Description]\nResolution: [What was done]\nCustomer satisfied: [Yes/No]\n\nFollow-up actions:\n- [Any remaining items]\n\nIf the customer contacts again within the cool-off period regarding this issue, the case will be reopened automatically.",
    category: "Closing",
    description: "Summarize the resolution steps and outcome for a closed case. Includes fields for root cause and preventive measures.",
    active: true,
    createdAt: "2026-02-24T02:00:00.000Z",
    updatedAt: "2026-02-24T02:00:00.000Z",
  },
  {
    id: "tpl-02",
    name: "Site Visit Required",
    title: "Site Visit Arranged",
    body: "A site visit has been arranged to resolve this case.\n\nVisit date: [DD/MM/YYYY]\nTime window: [Morning/Afternoon]\nTechnician: [Name]\nSite address: [Address]\n\nCustomer has been notified and confirmed availability. Access requirements: [Any special access notes].",
    category: "Field",
    description: "Schedule and document a required on-site visit. Captures logistics, contact info, and pre-visit checklist.",
    active: true,
    createdAt: "2026-02-19T04:00:00.000Z",
    updatedAt: "2026-02-19T04:00:00.000Z",
  },
  {
    id: "tpl-03",
    name: "Internal Handover",
    title: "Case Handover",
    body: "This case is being handed over to a new owner.\n\nPrevious owner: [Name]\nNew owner: [Name]\nReason for handover: [Reason]\n\nKey context:\n- [Summary point 1]\n- [Summary point 2]\n- [Current status and next steps]\n\nPlease review the full case history before contacting the customer.",
    category: "Internal",
    description: "Hand off a case to another team or agent with full context, history, and next steps.",
    active: true,
    createdAt: "2026-02-23T06:00:00.000Z",
    updatedAt: "2026-02-23T06:00:00.000Z",
  },
  {
    id: "tpl-04",
    name: "Billing Investigation",
    title: "Billing Escalation",
    body: "A billing investigation has been initiated for this account.\n\nAccount number: [Account #]\nDisputed amount: $[Amount]\nBilling period: [Period]\nNature of dispute: [Description]\n\nFindings will be documented here once the review is complete.",
    category: "Billing",
    description: "Document a billing dispute or discrepancy investigation with account details and disputed amounts.",
    active: true,
    createdAt: "2026-02-21T03:00:00.000Z",
    updatedAt: "2026-02-21T03:00:00.000Z",
  },
  {
    id: "tpl-05",
    name: "Escalation Follow-up",
    title: "Escalation Follow-up",
    body: "This case has been escalated to the relevant team for further review.\n\nEscalated to: [Team/Person]\nReason: [Brief reason for escalation]\nExpected response: [Timeframe]\n\nPlease monitor and follow up if no response is received within the expected timeframe.",
    category: "Escalation",
    description: "Track an escalation to a senior team or manager. Records who, why, and expected response time.",
    active: true,
    createdAt: "2026-02-22T01:00:00.000Z",
    updatedAt: "2026-02-22T01:00:00.000Z",
  },
  {
    id: "tpl-06",
    name: "Complaint Acknowledgement",
    title: "Complaint Acknowledged",
    body: "The customer's complaint has been formally acknowledged.\n\nComplaint category: [Category]\nRegulatory timeframe: 20 business days for resolution\nAcknowledgement sent via: [Email/Letter]\n\nNext steps:\n1. Investigate the root cause\n2. Prepare resolution options\n3. Contact customer with outcome",
    category: "Closing",
    description: "Formally acknowledge a customer complaint with regulatory timeframes and structured next steps.",
    active: true,
    createdAt: "2026-02-20T05:00:00.000Z",
    updatedAt: "2026-02-20T05:00:00.000Z",
  },
  {
    id: "tpl-07",
    name: "Onboarding Checklist",
    title: "New Customer Onboarding",
    body: "New customer onboarding initiated.\n\nChecklist:\n☐ Account details verified\n☐ Welcome pack sent\n☐ Meter installation scheduled\n☐ Tariff plan confirmed\n☐ Direct debit / payment method set up\n☐ First bill estimate provided\n\nNotes: [Any additional context]",
    category: "Onboarding",
    description: "Step-by-step checklist for setting up a new customer account with all required actions.",
    active: true,
    createdAt: "2026-02-18T02:00:00.000Z",
    updatedAt: "2026-02-18T02:00:00.000Z",
  },
  {
    id: "tpl-08",
    name: "Awaiting Customer Response",
    title: "Pending — Awaiting Customer",
    body: "Case placed on hold pending customer response.\n\nInformation requested:\n- [Item 1]\n- [Item 2]\n\nCustomer was contacted via [email/phone] on [date]. If no response is received within 5 business days, follow up with the customer.",
    category: "Internal",
    description: "Place a case on hold while waiting for customer-provided information or documentation.",
    active: true,
    createdAt: "2026-02-17T07:00:00.000Z",
    updatedAt: "2026-02-17T07:00:00.000Z",
  },
  {
    id: "tpl-09",
    name: "Escalation to Compliance",
    title: "Compliance Review Required",
    body: "This case requires compliance team review.\n\nRegulation/Policy: [Reference]\nPotential breach: [Description]\nEvidence: [Summary of supporting documents]\nDeadline for compliance response: [Date]\n\nPlease prioritise — regulatory reporting deadlines may apply.",
    category: "Escalation",
    description: "Flag a case for compliance team review when regulatory obligations or potential breaches are involved.",
    active: true,
    createdAt: "2026-02-16T04:00:00.000Z",
    updatedAt: "2026-02-16T04:00:00.000Z",
  },
  {
    id: "tpl-10",
    name: "Meter Read Discrepancy",
    title: "Meter Read Under Review",
    body: "A discrepancy has been identified with the customer's meter reading.\n\nMeter number: [Meter #]\nReported read: [Value]\nExpected range: [Range]\nLast confirmed read: [Value] on [Date]\n\nActions taken:\n1. Requested meter data validation from metering provider\n2. Estimated usage comparison generated\n3. Customer advised of investigation timeline (5 business days)",
    category: "Technical",
    description: "Investigate and document a meter reading discrepancy with validation steps and customer communication.",
    active: true,
    createdAt: "2026-02-15T03:00:00.000Z",
    updatedAt: "2026-02-15T03:00:00.000Z",
  },
];
