export const MOCK_EMAIL_TEMPLATES = [
  {
    id: "etpl-01",
    name: "Case Acknowledgement",
    subject: "Re: Your enquiry — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nThank you for contacting us. Your enquiry has been received and assigned case number {{caseNumber}}.\n\nOur team is currently reviewing the details and we will be in touch within 2 business days with an update.\n\nIf you have any additional information to share in the meantime, please reply to this email.\n\nKind regards,\n{{agentName}}\n{{teamName}}",
    category: "General",
    description: "Acknowledge receipt of a new customer enquiry or complaint with case reference.",
    active: true,
    createdAt: "2026-02-24T02:00:00.000Z",
    updatedAt: "2026-02-24T02:00:00.000Z",
  },
  {
    id: "etpl-02",
    name: "Information Request",
    subject: "Additional information needed — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nThank you for your patience while we review your case.\n\nTo progress this further, we require the following information:\n\n1. [Information item 1]\n2. [Information item 2]\n3. [Information item 3]\n\nPlease provide these details at your earliest convenience. If we do not hear from you within 5 business days, we may need to place your case on hold.\n\nKind regards,\n{{agentName}}\n{{teamName}}",
    category: "General",
    description: "Request additional information or documents from the customer to progress a case.",
    active: true,
    createdAt: "2026-02-23T06:00:00.000Z",
    updatedAt: "2026-02-23T06:00:00.000Z",
  },
  {
    id: "etpl-03",
    name: "Invoice Dispute Acknowledgement",
    subject: "Your billing enquiry — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nThank you for raising your billing concern. We have logged this under case number {{caseNumber}} and our billing team is now reviewing the details.\n\nDisputed invoice: [Invoice number]\nBilling period: [Period]\nDisputed amount: $[Amount]\n\nWe aim to complete our investigation within 10 business days. If we require any further information, we will be in touch.\n\nKind regards,\n{{agentName}}\nBilling Support",
    category: "Billing",
    description: "Acknowledge a billing dispute or invoice query with details of the investigation timeline.",
    active: true,
    createdAt: "2026-02-22T01:00:00.000Z",
    updatedAt: "2026-02-22T01:00:00.000Z",
  },
  {
    id: "etpl-04",
    name: "Resolution Notification",
    subject: "Case resolved — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nI am pleased to advise that your case {{caseNumber}} has been resolved.\n\nResolution summary:\n[Brief description of what was done]\n\nIf you have any questions about this outcome or believe the issue has not been fully addressed, please reply to this email and we will be happy to assist further.\n\nThank you for your patience throughout this process.\n\nKind regards,\n{{agentName}}\n{{teamName}}",
    category: "Closing",
    description: "Notify the customer that their case has been resolved with a summary of the outcome.",
    active: true,
    createdAt: "2026-02-21T03:00:00.000Z",
    updatedAt: "2026-02-21T03:00:00.000Z",
  },
  {
    id: "etpl-05",
    name: "Escalation Notification",
    subject: "Update on your case — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nI wanted to provide you with an update on your case {{caseNumber}}.\n\nYour matter has been escalated to our [Senior/Specialist] team for further review. This ensures your case receives the appropriate level of attention and expertise.\n\nYou can expect to hear from us within [timeframe] with a detailed update.\n\nWe appreciate your patience and take your concerns seriously.\n\nKind regards,\n{{agentName}}\n{{teamName}}",
    category: "Escalation",
    description: "Inform the customer that their case has been escalated for specialist review.",
    active: true,
    createdAt: "2026-02-20T05:00:00.000Z",
    updatedAt: "2026-02-20T05:00:00.000Z",
  },
  {
    id: "etpl-06",
    name: "Site Visit Confirmation",
    subject: "Site visit scheduled — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nA site visit has been scheduled in relation to your case {{caseNumber}}.\n\nVisit details:\n- Date: [DD/MM/YYYY]\n- Time window: [Morning/Afternoon]\n- Technician: [Name]\n- Site address: [Address]\n\nPlease ensure someone is available on site to provide access. If you need to reschedule, please contact us at least 24 hours in advance.\n\nKind regards,\n{{agentName}}\nField Operations",
    category: "Field",
    description: "Confirm a scheduled site visit with date, time, and access requirements.",
    active: true,
    createdAt: "2026-02-19T04:00:00.000Z",
    updatedAt: "2026-02-19T04:00:00.000Z",
  },
  {
    id: "etpl-07",
    name: "Payment Reminder",
    subject: "Payment reminder — Account {{accountNumber}}",
    body: "Dear {{customerName}},\n\nThis is a friendly reminder that your account has an outstanding balance of $[Amount] which was due on [Due date].\n\nIf you have already made payment, please disregard this notice. Otherwise, we kindly request that payment be made within the next 7 days to avoid any interruption to your services.\n\nPayment options:\n- Online: [Portal URL]\n- Phone: [Phone number]\n- Direct debit: Contact us to set up automatic payments\n\nIf you are experiencing financial difficulty, please reach out so we can discuss available support options.\n\nKind regards,\n{{agentName}}\nAccounts & Billing",
    category: "Billing",
    description: "Send a payment reminder for overdue accounts with payment options.",
    active: true,
    createdAt: "2026-02-18T02:00:00.000Z",
    updatedAt: "2026-02-18T02:00:00.000Z",
  },
  {
    id: "etpl-08",
    name: "Welcome / Onboarding",
    subject: "Welcome to Tally Energy — Getting started",
    body: "Dear {{customerName}},\n\nWelcome to Tally Energy! We are delighted to have you on board.\n\nHere is what happens next:\n\n1. Account setup — Your account has been created and your details are being verified\n2. Meter installation — Our team will contact you within [timeframe] to schedule installation\n3. First bill — You will receive your first bill approximately [timeframe] after your meter is live\n\nIn the meantime, you can:\n- Access your account online at [Portal URL]\n- Download our mobile app for usage monitoring\n- Review your tariff details in the attached welcome pack\n\nIf you have any questions, do not hesitate to reach out.\n\nKind regards,\n{{agentName}}\nCustomer Onboarding",
    category: "Onboarding",
    description: "Welcome a new customer with onboarding steps, portal access, and next steps.",
    active: true,
    createdAt: "2026-02-17T07:00:00.000Z",
    updatedAt: "2026-02-17T07:00:00.000Z",
  },
  {
    id: "etpl-09",
    name: "Meter Read Follow-up",
    subject: "Meter reading investigation update — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nFollowing your enquiry about a meter reading discrepancy, we have completed our investigation.\n\nFindings:\n- Meter number: [Meter #]\n- Reported reading: [Value]\n- Verified reading: [Value]\n- Outcome: [Description of findings]\n\n[If adjustment needed:] A billing adjustment of $[Amount] has been applied to your account and will be reflected on your next statement.\n\n[If no adjustment:] Our review confirms the meter reading is accurate. [Brief explanation.]\n\nIf you have any further questions, please do not hesitate to contact us.\n\nKind regards,\n{{agentName}}\nMetering Support",
    category: "Technical",
    description: "Provide results of a meter reading investigation with findings and any billing adjustments.",
    active: true,
    createdAt: "2026-02-16T04:00:00.000Z",
    updatedAt: "2026-02-16T04:00:00.000Z",
  },
  {
    id: "etpl-10",
    name: "Complaint Acknowledgement",
    subject: "Your complaint has been received — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nThank you for taking the time to share your concerns. Your complaint has been formally registered under case number {{caseNumber}}.\n\nWe take all complaints seriously and are committed to resolving this matter promptly. Under our complaint handling policy, we will:\n\n1. Investigate the issues you have raised\n2. Provide you with an initial response within 5 business days\n3. Aim to fully resolve your complaint within 20 business days\n\nIf at any stage you feel your complaint is not being handled satisfactorily, you have the right to escalate to the Energy Ombudsman.\n\nKind regards,\n{{agentName}}\nComplaints Resolution",
    category: "Escalation",
    description: "Formally acknowledge a customer complaint with regulatory timeframes and escalation rights.",
    active: true,
    createdAt: "2026-02-15T03:00:00.000Z",
    updatedAt: "2026-02-15T03:00:00.000Z",
  },
  {
    id: "etpl-11",
    name: "Contract Renewal Reminder",
    subject: "Your contract is due for renewal — {{accountNumber}}",
    body: "Dear {{customerName}},\n\nThis is to advise that your current energy contract is due to expire on [Expiry date].\n\nTo ensure continuity of your current rates and avoid reverting to our default tariff, we recommend reviewing your renewal options at your earliest convenience.\n\nWe can offer:\n- Renewal on current terms\n- Updated rate options based on your usage profile\n- Flexible contract lengths (1, 2, or 3 years)\n\nPlease contact us or reply to this email to arrange a time to discuss your options.\n\nKind regards,\n{{agentName}}\nCommercial Team",
    category: "Commercial",
    description: "Remind a customer that their contract is approaching expiry with renewal options.",
    active: true,
    createdAt: "2026-02-14T06:00:00.000Z",
    updatedAt: "2026-02-14T06:00:00.000Z",
  },
  {
    id: "etpl-12",
    name: "Outage Notification",
    subject: "Planned maintenance in your area — {{date}}",
    body: "Dear {{customerName}},\n\nWe are writing to advise of planned maintenance in your area that may result in a temporary interruption to your electricity supply.\n\nDetails:\n- Date: [DD/MM/YYYY]\n- Estimated time: [Start time] to [End time]\n- Affected area: [Location/suburb]\n- Reason: [Brief description of maintenance work]\n\nWe apologise for any inconvenience. If the work is completed ahead of schedule, power will be restored earlier.\n\nFor real-time updates, please visit [outage tracker URL] or call [phone number].\n\nKind regards,\n{{agentName}}\nNetwork Operations",
    category: "Technical",
    description: "Notify customers of planned maintenance or outages with timing and impact details.",
    active: true,
    createdAt: "2026-02-13T08:00:00.000Z",
    updatedAt: "2026-02-13T08:00:00.000Z",
  },
  {
    id: "etpl-13",
    name: "Hardship Support",
    subject: "Support options available — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nWe understand that managing energy costs can sometimes be challenging, and we want to ensure you are aware of the support options available to you.\n\nWe can assist with:\n- Flexible payment plans tailored to your circumstances\n- Reviewing your current tariff for potential savings\n- Information about government rebates and concessions\n- Referral to independent financial counselling services\n\nAll discussions are treated confidentially and there is no judgement — our goal is to help you find a manageable solution.\n\nPlease reply to this email or call us on [phone number] to discuss your options.\n\nKind regards,\n{{agentName}}\nCustomer Support",
    category: "Billing",
    description: "Offer hardship and financial difficulty support options to customers.",
    active: true,
    createdAt: "2026-02-12T05:00:00.000Z",
    updatedAt: "2026-02-12T05:00:00.000Z",
  },
  {
    id: "etpl-14",
    name: "Follow-up — No Response",
    subject: "Following up on your case — {{caseNumber}}",
    body: "Dear {{customerName}},\n\nWe are following up regarding your case {{caseNumber}}. We previously reached out on [date] requesting [information/action], but have not yet received a response.\n\nTo keep your case progressing, could you please provide the requested information at your earliest convenience?\n\nIf we do not hear from you within the next 5 business days, we may need to close this case. You are welcome to contact us at any time to reopen it.\n\nKind regards,\n{{agentName}}\n{{teamName}}",
    category: "General",
    description: "Follow up with a customer who has not responded to a previous request.",
    active: true,
    createdAt: "2026-02-11T03:00:00.000Z",
    updatedAt: "2026-02-11T03:00:00.000Z",
  },
  {
    id: "etpl-15",
    name: "Rate Review Summary",
    subject: "Your rate review summary — {{accountNumber}}",
    body: "Dear {{customerName}},\n\nFollowing our recent discussion, please find below a summary of the rate options we reviewed for your account.\n\nCurrent arrangement:\n- Tariff: [Current tariff]\n- Rate: $[Current rate]/MWh\n- Contract end: [Date]\n\nProposed options:\n1. [Option 1 — description and rate]\n2. [Option 2 — description and rate]\n3. [Option 3 — description and rate]\n\nI have attached a detailed comparison for your review. Please let us know which option you would like to proceed with, or if you would like to discuss further.\n\nKind regards,\n{{agentName}}\nCommercial Team",
    category: "Commercial",
    description: "Summarise rate review options discussed with a commercial customer.",
    active: true,
    createdAt: "2026-02-10T02:00:00.000Z",
    updatedAt: "2026-02-10T02:00:00.000Z",
  },
];
